; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Eternal Deck Builder"
#define MyAppVersion "Eternal Deck Builder - beta 1.0 "
#define MyAppPublisher "Zugzwang"
#define MyAppURL "http://www.example.com/"
#define MyAppExeName "Eternal.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{0E3BB79C-D3EA-403D-9C3B-473D2F90C403}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=D:\Eternal-Deck-Builder\docs\License.txt
OutputDir=D:\Eternal-Deck-Builder\Installer
OutputBaseFilename=Eternal_deck_builder_setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "D:\Eternal-Deck-Builder\bin\Eternal.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Eternal-Deck-Builder\docs\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\Eternal-Deck-Builder\Decks\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\Eternal-Deck-Builder\Cartes\*"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Eternal-Deck-Builder\bin\cfg.ini"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Eternal-Deck-Builder\bin\eternal.log"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Eternal-Deck-Builder\bin\Eternal_resource.rc"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Eternal-Deck-Builder\bin\icudt51.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Eternal-Deck-Builder\bin\icuin51.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Eternal-Deck-Builder\bin\icuuc51.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Eternal-Deck-Builder\bin\libgcc_s_dw2-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Eternal-Deck-Builder\bin\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Eternal-Deck-Builder\bin\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Eternal-Deck-Builder\bin\Qt5Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Eternal-Deck-Builder\bin\Qt5Gui.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Eternal-Deck-Builder\bin\Qt5Network.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Eternal-Deck-Builder\bin\Qt5PrintSupport.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Eternal-Deck-Builder\bin\Qt5Sql.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Eternal-Deck-Builder\bin\Qt5Widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Eternal-Deck-Builder\bin\VtesCardsListDB"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

